name: Feature Branch Push CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!develop'

jobs:

  test:
    name: CI Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decode google-services.json
        env:
          FIREBASE_JSON_ARIZONA: ${{ secrets.FIREBASE_JSON_ARIZONA }}
          FIREBASE_JSON_MAIN: ${{ secrets.FIREBASE_JSON_MAIN }}
          FIREBASE_JSON_FAKE: ${{ secrets.FIREBASE_JSON_FAKE}}
        run: |
          echo $FIREBASE_SECRET > app/src/calibrationArizona/google-services.json |
          echo $FIREBASE_JSON_MAIN > app/src/calibrationGlobal/google-services.json |
          echo $FIREBASE_JSON_FAKE > app/src/production/google-services.json
      - name: Decode debug.keystore
        env:
          DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}
        run: echo "$DEBUG_KEYSTORE" | base64 --decode > debug.keystore
      - name: Clean, Build
        run: bash ./gradlew clean assemble -PVERIFICATION_API_KEY=$VERIFICATION_API_KEY -PSERVER_VERIFICATION_ENDPOINT=$SERVER_VERIFICATION_ENDPOINT -PSERVER_UPLOAD_ENDPOINT=$SERVER_UPLOAD_ENDPOINT -PSERVER_DOWNLOAD_ENDPOINT=$SERVER_DOWNLOAD_ENDPOINT --stacktrace
      - name: Lint
        run: bash ./gradlew lint -PVERIFICATION_API_KEY=$VERIFICATION_API_KEY -PSERVER_VERIFICATION_ENDPOINT=$SERVER_VERIFICATION_ENDPOINT -PSERVER_UPLOAD_ENDPOINT=$SERVER_UPLOAD_ENDPOINT -PSERVER_DOWNLOAD_ENDPOINT=$SERVER_DOWNLOAD_ENDPOINT
      - name: Test
        run: bash ./gradlew app:test -Pcoverage -PVERIFICATION_API_KEY=$VERIFICATION_API_KEY -PSERVER_VERIFICATION_ENDPOINT=$SERVER_VERIFICATION_ENDPOINT -PSERVER_UPLOAD_ENDPOINT=$SERVER_UPLOAD_ENDPOINT -PSERVER_DOWNLOAD_ENDPOINT=$SERVER_DOWNLOAD_ENDPOINT


