name: Feature Branch Push CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!develop'

jobs:

  test:
    name: CI Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Clean, Build
      run: bash ./gradlew clean assemble --stacktrace
    - name: Lint
      run: bash ./gradlew lint
    - name: Test
      run: bash ./gradlew -Pcoverage app:test


